export const FETCHED_WEIGHT_SUCCESS =
  'FETCHED_WEIGHT_SUCCESS'
export const POST_WEIGHT_TO_DATABASE =
  'POST_WEIGHT_TO_DATABASE'
export const CHANGE_NAV_ITEM_ACTIVE =
  'CHANGE_NAV_ITEM_ACTIVE'
export const CHANGE_TAB_ITEM_ACTIVE =
  'CHANGE_TAB_ITEM_ACTIVE'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const SAVE_USERINFO = 'SAVE_USERINFO'
export const LOGOUT = 'LOGOUT'
