export const FETCHED_WEIGHT_SUCCESS =
  'FETCHED_WEIGHT_SUCCESS'
export const POST_WEIGHT_TO_DATABASE =
  'POST_WEIGHT_TO_DATABASE'
export const CHANGE_NAV_ITEM_ACTIVE =
  'CHANGE_NAV_ITEM_ACTIVE'
export const CHANGE_TAB_ITEM_ACTIVE =
  'CHANGE_TAB_ITEM_ACTIVE'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const SAVE_USERINFO = 'SAVE_USERINFO'
export const LOGOUT = 'LOGOUT'
export const TOOGLE_SEARCH_VISIBLE =
  'TOOGLE_SEARCH_VISIBLE'
export const TOOGLE_SEARCH_HIDDEN =
  'TOOGLE_SEARCH_HIDDEN'
export const GET_REGRET_SUCCESS =
  'GET_REGRET_SUCCESS'
export const GET_REGRET_REQUEST =
  'GET_REGRET_REQUEST'
export const GET_REQUEST_FAILED =
  'GET_REQUEST_FAILED'
export const POST_REGRET_TO_DATABASE =
  'POST_REGRET_TO_DATABASE'
export const GET_COMMENT_SUCCESS =
  'GET_COMMENT_SUCCESS'
export const GET_COMMENT_REQUEST =
  'GET_COMMENT_REQUEST'
export const POST_COMMENT_TO_DATABASE =
  'POST_COMMENT_TO_DATABASE'
