export const FETCHED_WEIGHT_SUCCESS =
  'FETCHED_WEIGHT_SUCCESS'
export const POST_WEIGHT_TO_DATABASE =
  'POST_WEIGHT_TO_DATABASE'
export const CHANGE_NAV_ITEM_ACTIVE =
  'CHANGE_NAV_ITEM_ACTIVE'
export const CHANGE_TAB_ITEM_ACTIVE =
  'CHANGE_TAB_ITEM_ACTIVE'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const SAVE_USERINFO = 'SAVE_USERINFO'
export const LOGOUT = 'LOGOUT'
export const TOOGLE_SEARCH_VISIBLE =
  'TOOGLE_SEARCH_VISIBLE'
export const TOOGLE_SEARCH_HIDDEN =
  'TOOGLE_SEARCH_HIDDEN'
export const GET_SHORTLOG_SUCCESS =
  'GET_SHORTLOG_SUCCESS'
export const GET_SHORTLOG_REQUEST =
  'GET_SHORTLOG_REQUEST'
export const GET_REQUEST_FAILED =
  'GET_REQUEST_FAILED'
export const POST_SHORTLOG_TO_DATABASE =
  'POST_SHORTLOG_TO_DATABASE'
export const GET_LONGLOG_SUCCESS =
  'GET_LONGLOG_SUCCESS'
export const GET_LONGLOG_REQUEST =
  'GET_LONGLOG_REQUEST'
export const POST_LONGLOG_TO_DATABASE =
  'POST_LONGLOG_TO_DATABASE'
export const SET_TODAY_DATE = 'SET_TODAY_DATE'
export const SET_TODAY_DAY = 'SET_TODAY_DAY'
